# Generated by Django 6.0.4 on 2026-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
